export enum AuthActionType {
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  AUTH_ERROR = "AUTH_ERROR",
  AUTH_REQUEST = "AUTH_REQUEST",
  LOGIN_FAIL = "LOGIN_FAIL",
  REGISTER_FAIL = "REGISTER_FAIL",
}
